// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc219.Zachstest;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Servo motorsServo1;
    public static Servo motorsServo2;
    public static CANJaguar driveBaseLeftMotor;
    public static CANJaguar driveBaseRightMotor;
    public static RobotDrive driveBaseRobotDrive21;
    public static SpeedController gripperVictor;
    public static SpeedController wristSpeedController1;
    public static AnalogPotentiometer wristAnalogPotentiometer1;
    public static SpeedController elevatorVictor;
    public static AnalogPotentiometer elevatorAnalogPotentiometer1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        motorsServo1 = new Servo(0);
        LiveWindow.addActuator("Motors", "Servo 1", motorsServo1);
        
        motorsServo2 = new Servo(1);
        LiveWindow.addActuator("Motors", "Servo 2", motorsServo2);
        
        driveBaseLeftMotor = new CANJaguar(3);
        
        
        driveBaseRightMotor = new CANJaguar(2);
        
        
        driveBaseRobotDrive21 = new RobotDrive(driveBaseLeftMotor, driveBaseRightMotor);
        
        driveBaseRobotDrive21.setSafetyEnabled(true);
        driveBaseRobotDrive21.setExpiration(0.1);
        driveBaseRobotDrive21.setSensitivity(0.5);
        driveBaseRobotDrive21.setMaxOutput(1.0);
        

        gripperVictor = new Talon(6);
        LiveWindow.addActuator("Gripper", "Victor", (Talon) gripperVictor);
        
        wristSpeedController1 = new Talon(5);
        LiveWindow.addActuator("Wrist", "Speed Controller 1", (Talon) wristSpeedController1);
        
        wristAnalogPotentiometer1 = new AnalogPotentiometer(2, 1.0, 0.0);
        LiveWindow.addSensor("Wrist", "Analog Potentiometer 1", wristAnalogPotentiometer1);
        
        elevatorVictor = new Talon(2);
        LiveWindow.addActuator("Elevator", "Victor", (Talon) elevatorVictor);
        
        elevatorAnalogPotentiometer1 = new AnalogPotentiometer(4, 1.0, 0.0);
        LiveWindow.addSensor("Elevator", "Analog Potentiometer 1", elevatorAnalogPotentiometer1);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
